You made it to Chapter 2, huh? 
Things get a bit weird around here, Doors hide secrets, but not all secrets are good...
Can you feel the cold? It's not just wind...
They say it's stories from the past...
Go on but just be careful....What you see might not be the whole story...